// =============================================================================
// DATOS: CODEX, BLUEPRINT, MISIONES, FRAGMENTOS DE MEMORIA, TERMINALES HISTÓRICAS
// =============================================================================
// Codex: lat/cap = latencia y capacidad relativas (1 = mínima, 5 = máxima; 0 = no aplica)
const CODEX = [
  // FUNDAMENTOS
  { id: 'hwsw', cat: 'FUNDAMENTOS', name: 'Hardware y software', concept: 'hardwareBasics', def: 'El hardware es la parte física de un sistema; el software, las instrucciones y datos que lo dirigen.', func: 'El hardware ejecuta; el software decide qué ejecutar.', inp: 'Energía y señales (hardware); datos (software).', out: 'Resultados físicos y lógicos.', conn: 'El software vive en memoria y almacenamiento; el hardware lo lee y lo ejecuta.', lat: 0, cap: 0, ex: 'Un teclado (hardware) y su driver (software).', err: 'Creer que el sistema operativo o el firmware son hardware porque «vienen con la máquina».', byte: 'Una cosa es la guitarra y otra la canción. Las dos hacen falta.' },
  { id: 'ipo', cat: 'FUNDAMENTOS', name: 'Modelo entrada–proceso–memoria–salida', concept: 'hardwareBasics', def: 'Patrón básico de todo sistema de cómputo.', func: 'Capturar datos, transformarlos, conservarlos y devolver resultados.', inp: 'Dispositivos de entrada.', out: 'Dispositivos de salida.', conn: 'CPU en el centro; memoria a su lado; E/S en los bordes.', lat: 0, cap: 0, ex: 'Pulsar una tecla y ver la letra en pantalla recorre todo el modelo.', err: 'Pensar que cada etapa funciona aislada.', byte: 'Hasta una calculadora cumple el modelo. Me siento menos especial.' },
  { id: 'firmware', cat: 'FUNDAMENTOS', name: 'Firmware (BIOS/UEFI)', concept: 'hardwareBasics', def: 'Software grabado en memoria no volátil de un dispositivo.', func: 'Inicializar el hardware y arrancar el sistema operativo.', inp: 'Encendido del equipo.', out: 'Hardware configurado y el control al cargador del SO.', conn: 'Chip flash de la placa base.', lat: 2, cap: 1, ex: 'El POST que prueba CPU, memoria y vídeo al arrancar.', err: 'Creer que es hardware porque está soldado.', byte: 'El recipiente es hardware; lo que contiene, no.' },
  // PLACA BASE
  { id: 'mb', cat: 'PLACA BASE', name: 'Placa base', concept: 'motherboard', def: 'Circuito principal que conecta y alimenta todos los componentes.', func: 'Proveer caminos (pistas, buses), energía (VRM) y coordinación (chipset).', inp: 'Energía de la fuente y señales de todos los componentes.', out: 'Comunicación entre componentes.', conn: 'CPU, RAM, GPU, almacenamiento, E/S y fuente.', lat: 0, cap: 0, ex: 'Sockets, ranuras DIMM, PCIe, M.2 y conectores de energía.', err: 'Pensar que es «un soporte» pasivo: es la red de comunicación del sistema.', byte: 'La ciudad no es sus edificios: es cómo se conectan.' },
  { id: 'vrm', cat: 'PLACA BASE', name: 'VRM (regulador de voltaje)', concept: 'motherboard', def: 'Circuito que convierte los 12 V de la fuente en el voltaje bajo y estable que pide la CPU.', func: 'Alimentar la CPU con precisión, incluso cuando su demanda cambia en microsegundos.', inp: '12 V de la fuente.', out: '~0,8–1,4 V para la CPU.', conn: 'Junto al socket de la CPU.', lat: 0, cap: 0, ex: 'Las fases de alimentación con disipadores alrededor del socket.', err: 'Ignorarlo: un VRM débil provoca inestabilidad y pérdida de rendimiento.', byte: 'Sin energía estable, hasta la CPU más rápida se equivoca.' },
  { id: 'chipset', cat: 'PLACA BASE', name: 'Chipset', concept: 'motherboard', def: 'Conjunto de controladores que gestiona periféricos y comunicaciones secundarias.', func: 'Conectar USB, SATA, red y ranuras adicionales con la CPU.', inp: 'Peticiones de periféricos.', out: 'Datos hacia y desde la CPU.', conn: 'CPU (enlace dedicado), puertos y ranuras.', lat: 3, cap: 0, ex: 'Los puertos USB traseros pasan por el chipset.', err: 'Confundirlo con la CPU.', byte: 'El chipset es el intercambiador de la ciudad.' },
  { id: 'pcie', cat: 'PLACA BASE', name: 'PCI Express', concept: 'motherboard', def: 'Interfaz de expansión formada por carriles serie de alta velocidad.', func: 'Conectar tarjetas gráficas, SSD NVMe y otras expansiones.', inp: 'Datos desde la CPU o el chipset.', out: 'Datos hacia el dispositivo.', conn: 'x1, x4, x8, x16: número de carriles.', lat: 2, cap: 0, ex: 'Una GPU en PCIe x16 dispone de 16 carriles en paralelo.', err: 'Creer que x16 indica la versión: indica los carriles.', byte: 'Más carriles, más tráfico a la vez. Como las autopistas.' },
  { id: 'gpu', cat: 'PLACA BASE', name: 'GPU', concept: 'parallelism', def: 'Procesador con miles de núcleos simples, especializado en trabajo paralelo.', func: 'Calcular gráficos y cualquier tarea que aplique la misma operación a muchos datos.', inp: 'Datos y órdenes de la CPU.', out: 'Imágenes al monitor o resultados de cálculo.', conn: 'PCIe x16 y su propia memoria (VRAM).', lat: 2, cap: 3, ex: 'Colorear millones de píxeles a la vez.', err: 'Creer que siempre es mejor que la CPU: sólo lo es para trabajo paralelo.', byte: 'La CPU es un chef; la GPU, mil cocineros haciendo tostadas.' },
  // CPU
  { id: 'cpu', cat: 'CPU', name: 'CPU (unidad central de procesamiento)', concept: 'cpu', def: 'Circuito que busca, decodifica y ejecuta las instrucciones de los programas.', func: 'Transformar datos siguiendo instrucciones, ciclo a ciclo.', inp: 'Instrucciones y datos desde memoria; interrupciones de E/S.', out: 'Resultados en registros y memoria; órdenes a los dispositivos.', conn: 'RAM (buses), caché interna, chipset, PCIe.', lat: 1, cap: 1, ex: 'Una CPU a 4 GHz completa 4.000 millones de ciclos por segundo.', err: 'Pensar que la CPU «guarda» los programas: los ejecuta desde la memoria.', byte: 'Antes pensaba que la CPU lo hacía todo. En realidad pasa la mitad del tiempo esperando.' },
  { id: 'cu', cat: 'CPU', name: 'Unidad de Control', concept: 'cpu', def: 'Parte de la CPU que interpreta instrucciones y coordina al resto.', func: 'Generar las señales de control de cada paso del ciclo.', inp: 'La instrucción del IR y las banderas.', out: 'Señales para ALU, registros, memoria y buses.', conn: 'Todos los bloques internos de la CPU.', lat: 1, cap: 0, ex: 'Al decodificar ADD, activa la suma en la ALU y elige los registros.', err: 'Creer que hace cálculos: sólo dirige.', byte: 'La directora de orquesta no toca, pero sin ella no suena nada.' },
  { id: 'alu', cat: 'CPU', name: 'ALU (unidad aritmético-lógica)', concept: 'alu', def: 'Circuito que realiza operaciones aritméticas (suma, resta) y lógicas (AND, OR, XOR, NOT).', func: 'Calcular resultados y actualizar las banderas (Z, N, C, V).', inp: 'Operandos desde registros y la operación elegida.', out: 'Resultado y banderas.', conn: 'Registros y Unidad de Control.', lat: 1, cap: 0, ex: 'Comparar A y B restándolos y mirando la bandera Z.', err: 'Creer que tiene un circuito de resta: suma el complemento a dos.', byte: 'Antes veía cajas. Ahora veo decisiones.' },
  { id: 'registers', cat: 'CPU', name: 'Registros', concept: 'registers', def: 'Pequeñas memorias ultrarrápidas dentro del núcleo.', func: 'Sostener los datos y direcciones que la CPU usa en este mismo instante.', inp: 'Resultados de la ALU y datos cargados de memoria.', out: 'Operandos para la ALU y direcciones para la memoria.', conn: 'ALU, Unidad de Control, caché L1.', lat: 1, cap: 1, ex: 'PC, IR, MAR, MDR, acumulador, banderas.', err: 'Confundir el PC (dirección) con el IR (instrucción).', byte: 'REG habla rápido porque sabe que no le queda mucho espacio.' },
  { id: 'pc', cat: 'CPU', name: 'Contador de Programa (PC)', concept: 'registers', def: 'Registro que guarda la dirección de la próxima instrucción.', func: 'Avanzar tras cada FETCH o saltar si una instrucción lo indica.', inp: 'Incremento automático o destino de un salto.', out: 'Dirección hacia el MAR.', conn: 'MAR, Unidad de Control.', lat: 1, cap: 1, ex: 'JUMP 0x80 pone el PC a 0x80.', err: 'Creer que contiene la instrucción.', byte: 'Es el marcapáginas del programa.' },
  { id: 'clock', cat: 'CPU', name: 'Reloj', concept: 'cpu', def: 'Señal periódica que sincroniza todos los pasos de la CPU.', func: 'Marcar cuándo los registros capturan nuevos valores (flanco de subida).', inp: 'Oscilador de cuarzo y multiplicadores.', out: 'Pulsos a toda la CPU.', conn: 'Todos los registros y la lógica secuencial.', lat: 0, cap: 0, ex: '3 GHz = 3.000 millones de flancos por segundo.', err: 'Creer que más frecuencia siempre es más rendimiento (importa el IPC).', byte: 'Toda la ciudad baila al mismo ritmo. Si alguien se adelanta, todo se rompe.' },
  { id: 'cycle', cat: 'CPU', name: 'Ciclo de instrucción', concept: 'fetchDecodeExecute', def: 'Secuencia FETCH → DECODE → EXECUTE → WRITE BACK que sigue cada instrucción.', func: 'Convertir una instrucción guardada en memoria en un cambio real de estado.', inp: 'Instrucción apuntada por el PC.', out: 'Resultado escrito y PC actualizado.', conn: 'Memoria, Unidad de Control, ALU, registros.', lat: 0, cap: 0, ex: 'ADD R1, R2: traer, decodificar, sumar, guardar en R1.', err: 'Pensar que FETCH trae el dato: trae la instrucción.', byte: 'No basta con leer el log. Hay que decodificarlo.' },
  { id: 'pipeline', cat: 'CPU', name: 'Pipeline (segmentación)', concept: 'fetchDecodeExecute', def: 'Técnica que solapa las etapas de varias instrucciones.', func: 'Aumentar el throughput: mientras una instrucción se ejecuta, la siguiente se decodifica.', inp: 'Flujo de instrucciones.', out: 'Más instrucciones terminadas por ciclo.', conn: 'Todas las etapas del ciclo.', lat: 0, cap: 0, ex: 'Un riesgo de datos obliga a esperar si una instrucción necesita un resultado pendiente.', err: 'Creer que reduce la latencia de cada instrucción: mejora el total.', byte: 'Una lavandería con lavadora, secadora y plancha trabajando a la vez.' },
  { id: 'gates', cat: 'CPU', name: 'Compuertas lógicas', concept: 'alu', def: 'Circuitos elementales que combinan bits: AND, OR, NOT, XOR, NAND, NOR.', func: 'Construir cualquier cálculo a partir de decisiones binarias.', inp: 'Uno o dos bits.', out: 'Un bit.', conn: 'Forman sumadores, comparadores, registros y la ALU entera.', lat: 1, cap: 0, ex: 'Un semisumador: XOR para la suma y AND para el acarreo.', err: 'Pensar que NAND es «rara»: con ella se construye todo.', byte: 'NEXO OR NULL. Mmm. ¿Y si fuera AND?' },
  { id: 'binary', cat: 'CPU', name: 'Aritmética binaria', concept: 'alu', def: 'Representación y operación de números en base 2.', func: 'Sumar con acarreo, restar con complemento a dos, desplazar para multiplicar.', inp: 'Números binarios.', out: 'Resultados binarios y banderas.', conn: 'ALU.', lat: 0, cap: 0, ex: '0101 + 0011 = 01000 (5 + 3 = 8).', err: 'Olvidar el acarreo final o descartarlo cuando importa.', byte: '1 + 1 = 10. Tardé una semana en dejar de reírme.' },
  // MEMORIA
  { id: 'hierarchy', cat: 'MEMORIA', name: 'Jerarquía de memoria', concept: 'cache', def: 'Organización en niveles: registros, cachés, RAM, almacenamiento.', func: 'Dar la ilusión de una memoria grande y rápida a la vez.', inp: 'Peticiones de la CPU.', out: 'Datos desde el nivel más cercano que los tenga.', conn: 'Cada nivel es la «caché» del siguiente.', lat: 0, cap: 0, ex: 'Un acceso que falla en L1 y L2 pero acierta en L3.', err: 'Creer que se elige un solo tipo de memoria: todos trabajan juntos.', byte: 'A más profundidad, más capacidad y más espera. Como una biblioteca.' },
  { id: 'cache', cat: 'MEMORIA', name: 'Caché', concept: 'cache', def: 'Memoria pequeña y rápida con copias de datos recientes de la RAM.', func: 'Evitar que la CPU espere a la RAM en cada acceso.', inp: 'Líneas de datos desde la RAM.', out: 'Datos a los registros en pocos ciclos.', conn: 'Dentro de la CPU: L1 por núcleo, L3 compartida.', lat: 2, cap: 2, ex: 'Cache hit en L1: ~4 ciclos. Miss hasta RAM: ~200.', err: 'Creer que reemplaza a la RAM.', byte: 'Ahora entiendo por qué todo parecía rápido hasta que dejaba de estarlo.' },
  { id: 'locality', cat: 'MEMORIA', name: 'Localidad', concept: 'cache', def: 'Tendencia de los programas a reutilizar datos (temporal) y a usar datos cercanos (espacial).', func: 'Es la razón por la que las cachés funcionan.', inp: 'Patrones de acceso.', out: 'Aciertos de caché.', conn: 'Líneas de caché, prefetching.', lat: 0, cap: 0, ex: 'Recorrer un array fila a fila aprovecha la localidad espacial.', err: 'Recorrer datos en saltos grandes y culpar a la caché.', byte: 'Si usas algo, probablemente usarás a sus vecinos. Como los tuppers.' },
  { id: 'ram', cat: 'MEMORIA', name: 'RAM', concept: 'ram', def: 'Memoria principal, de acceso aleatorio y volátil.', func: 'Guardar los programas y datos en uso.', inp: 'Datos desde almacenamiento y resultados de la CPU.', out: 'Instrucciones y datos hacia las cachés.', conn: 'Controlador de memoria de la CPU mediante buses.', lat: 3, cap: 4, ex: '16 GB con latencia de ~200 ciclos.', err: 'Creer que más RAM siempre acelera: sólo si faltaba.', byte: '¿Viste cómo desapareció al cortar energía? Eso es lo importante.' },
  { id: 'ssd', cat: 'MEMORIA', name: 'Almacenamiento (SSD / HDD)', concept: 'storage', def: 'Memoria no volátil de gran capacidad.', func: 'Conservar datos y programas sin energía.', inp: 'Archivos a guardar.', out: 'Archivos cargados a la RAM.', conn: 'M.2/NVMe, SATA, chipset.', lat: 5, cap: 5, ex: 'Un SSD responde en ~100 µs; un HDD, en ~10 ms.', err: 'Creer que la CPU ejecuta directamente desde él.', byte: 'El sótano de la torre: todo está ahí, pero bajar cuesta.' },
  { id: 'vmem', cat: 'MEMORIA', name: 'Memoria virtual', concept: 'ram', def: 'Mecanismo que usa el almacenamiento como extensión de la RAM.', func: 'Permitir ejecutar más de lo que cabe en RAM, a costa de velocidad.', inp: 'Páginas que no caben en RAM.', out: 'Páginas movidas entre RAM y almacenamiento.', conn: 'Sistema operativo, MMU, SSD.', lat: 5, cap: 5, ex: 'RAM al 98% y SSD al 100%: paginación constante.', err: 'Confundirla con más memoria real.', byte: 'Funciona como tomar prestado. Hasta que hay que devolverlo.' },
  // BUSES
  { id: 'busdata', cat: 'BUSES', name: 'Bus de datos', concept: 'buses', def: 'Conjunto de líneas que transporta los valores.', func: 'Llevar datos entre CPU, memoria y dispositivos, en ambos sentidos.', inp: 'Valores a escribir o leídos.', out: 'Los mismos valores en el destino.', conn: 'CPU, memoria, E/S.', lat: 2, cap: 0, ex: 'El dato 42 viaja hacia la RAM al escribir.', err: 'Pensar que todo número hexadecimal es una dirección.', byte: 'El QUÉ.' },
  { id: 'busaddr', cat: 'BUSES', name: 'Bus de direcciones', concept: 'buses', def: 'Líneas que indican la posición de memoria o el puerto al que se accede.', func: 'Seleccionar DÓNDE leer o escribir.', inp: 'Dirección generada por la CPU (o el DMA).', out: 'Selección de posición en memoria o dispositivo.', conn: 'Normalmente unidireccional desde la CPU.', lat: 2, cap: 0, ex: '16 líneas → 65.536 posiciones.', err: 'Creer que transporta los datos.', byte: 'El DÓNDE.' },
  { id: 'busctrl', cat: 'BUSES', name: 'Bus de control', concept: 'buses', def: 'Líneas de órdenes y sincronización.', func: 'Indicar CUÁNDO y CÓMO: leer, escribir, reloj, interrupciones, reset.', inp: 'Órdenes de la CPU y peticiones de dispositivos.', out: 'Coordinación de la transferencia.', conn: 'Todos los componentes.', lat: 1, cap: 0, ex: 'La señal LEER junto a una dirección.', err: 'Olvidar que también llegan señales hacia la CPU (IRQ).', byte: 'El CUÁNDO y el CÓMO. Sin él, datos y direcciones no se entienden.' },
  { id: 'bandwidth', cat: 'BUSES', name: 'Ancho de banda', concept: 'buses', def: 'Cantidad de datos que un canal transfiere por segundo.', func: 'Medir la capacidad de comunicación.', inp: 'Anchura del bus y frecuencia.', out: 'Bytes por segundo.', conn: 'Buses, PCIe, memoria.', lat: 0, cap: 0, ex: '64 bits a 100 MHz = 800 MB/s.', err: 'Confundirlo con la latencia.', byte: 'Una autopista ancha no hace que cada coche llegue antes.' },
  // E/S
  { id: 'ioctrl', cat: 'E/S', name: 'Controladores y drivers', concept: 'io', def: 'Hardware (controlador) y software (driver) que permiten hablar con un dispositivo.', func: 'Traducir órdenes genéricas a las señales concretas de cada dispositivo.', inp: 'Peticiones del sistema operativo.', out: 'Operaciones del dispositivo.', conn: 'Chipset, buses, sistema operativo.', lat: 3, cap: 0, ex: 'Una impresora detectada pero sin driver no imprime.', err: 'Pensar que «detectado» significa «funcionando».', byte: 'Hablar el mismo idioma también es parte del hardware.' },
  { id: 'interrupt', cat: 'E/S', name: 'Interrupción', concept: 'interrupts', def: 'Señal que pide a la CPU atender un evento urgente.', func: 'Evitar que la CPU pregunte constantemente (polling).', inp: 'Línea IRQ de un dispositivo.', out: 'Salto a la rutina de servicio (ISR).', conn: 'Controlador de interrupciones, bus de control.', lat: 1, cap: 0, ex: 'Una tecla pulsada interrumpe el proceso actual un instante.', err: 'Olvidar guardar el estado antes de la ISR.', byte: 'Aceptar información inesperada sin abandonar lo que haces. Me cuesta.' },
  { id: 'isr', cat: 'E/S', name: 'ISR (rutina de servicio)', concept: 'interrupts', def: 'Código que atiende una interrupción concreta.', func: 'Responder al dispositivo y devolver el control rápidamente.', inp: 'Estado guardado y datos del dispositivo.', out: 'Dispositivo atendido.', conn: 'Tabla de vectores de interrupción.', lat: 1, cap: 0, ex: 'La ISR del teclado lee el código de la tecla.', err: 'Hacer ISR largas que bloquean el sistema.', byte: 'Entrar, arreglar, salir. Sin dramas.' },
  { id: 'polling', cat: 'E/S', name: 'Polling (sondeo)', concept: 'io', def: 'Técnica en la que la CPU consulta periódicamente a un dispositivo.', func: 'Detectar eventos de forma sencilla.', inp: 'Estado del dispositivo.', out: 'Detección del evento (con retraso).', conn: 'CPU y registros del dispositivo.', lat: 3, cap: 0, ex: 'Sondear 1.000 veces por segundo desperdicia CPU.', err: 'Creer que sondear más rápido lo resuelve todo.', byte: '¿Ya llegamos? ¿Ya llegamos? ¿Ya llegamos?' },
  { id: 'dma', cat: 'E/S', name: 'DMA (acceso directo a memoria)', concept: 'io', def: 'Mecanismo que transfiere datos entre dispositivo y memoria sin la CPU.', func: 'Liberar a la CPU durante transferencias grandes.', inp: 'Orden de transferencia de la CPU.', out: 'Datos en memoria e interrupción al terminar.', conn: 'Controlador DMA, buses, RAM.', lat: 2, cap: 0, ex: 'Cargar un archivo del SSD a la RAM.', err: 'Pensar que la CPU copia cada byte.', byte: 'Delegar también es arquitectura.' },
  // RENDIMIENTO
  { id: 'freqipc', cat: 'RENDIMIENTO', name: 'Frecuencia e IPC', concept: 'performance', def: 'Frecuencia: ciclos por segundo. IPC: instrucciones por ciclo.', func: 'Juntas estiman las instrucciones por segundo.', inp: 'Diseño de la CPU y reloj.', out: 'Rendimiento aproximado.', conn: 'Reloj, pipeline, cachés.', lat: 0, cap: 0, ex: '3 GHz × IPC 2 supera a 4 GHz × IPC 1.', err: 'Comparar CPUs sólo por GHz.', byte: 'El número grande de la caja no cuenta toda la historia.' },
  { id: 'latthr', cat: 'RENDIMIENTO', name: 'Latencia y throughput', concept: 'performance', def: 'Latencia: tiempo que tarda una operación. Throughput: operaciones por unidad de tiempo.', func: 'Describir el rendimiento desde dos ángulos distintos.', inp: 'Mediciones.', out: 'Diagnóstico.', conn: 'Todo el sistema.', lat: 0, cap: 0, ex: 'Una autopista ancha: mucho throughput aunque cada coche tarde.', err: 'Usarlas como sinónimos.', byte: 'REDUCIR TODA LATENCIA EVITABLE. Ahora esa frase me da escalofríos.' },
  { id: 'parallel', cat: 'RENDIMIENTO', name: 'Paralelismo y núcleos', concept: 'parallelism', def: 'Ejecución simultánea de tareas independientes en varios núcleos.', func: 'Aumentar el trabajo total por segundo.', inp: 'Tareas divisibles.', out: 'Resultados en menos tiempo total.', conn: 'Núcleos, caché compartida, planificador.', lat: 0, cap: 0, ex: 'Procesar píxeles de una imagen en paralelo.', err: 'Creer que cualquier programa se acelera con más núcleos.', byte: 'Dos manos ayudan... si la tarea se puede repartir.' },
  { id: 'amdahl', cat: 'RENDIMIENTO', name: 'Ley de Amdahl', concept: 'parallelism', def: 'La aceleración máxima está limitada por la parte secuencial.', func: 'Predecir el beneficio real de añadir núcleos.', inp: 'Fracción paralelizable y número de núcleos.', out: 'Aceleración = 1 / ((1 − p) + p/n).', conn: 'Diseño de software y hardware.', lat: 0, cap: 0, ex: 'Con un 25% secuencial, nunca pasarás de 4×.', err: 'Esperar aceleración lineal.', byte: 'Siempre hay una parte que nadie puede hacer por ti.' },
  { id: 'bottleneck', cat: 'RENDIMIENTO', name: 'Cuello de botella', concept: 'bottlenecks', def: 'El recurso que limita el rendimiento del sistema completo.', func: 'Indicar dónde mejorar tiene efecto real.', inp: 'Cargas de CPU, RAM, disco, GPU, red, temperatura.', out: 'Diagnóstico.', conn: 'Todos los componentes.', lat: 0, cap: 0, ex: 'RAM 98% y SSD 100% con CPU al 25%: falta RAM.', err: 'Mejorar el componente que no limita.', byte: 'No preguntes qué pieza es la mejor. Pregunta cuál hace esperar a las demás.' },
  { id: 'thermal', cat: 'RENDIMIENTO', name: 'Temperatura y throttling', concept: 'performance', def: 'Reducción automática de frecuencia para evitar daños por calor.', func: 'Proteger el hardware a costa del rendimiento.', inp: 'Sensores de temperatura.', out: 'Menor frecuencia y voltaje.', conn: 'CPU, VRM, ventiladores, disipadores.', lat: 0, cap: 0, ex: 'Un ventilador detenido baja la CPU al 30% de su frecuencia.', err: 'Culpar a la CPU cuando el problema es la refrigeración.', byte: 'Correr más rápido de lo que puedes enfriar no es correr: es romperse.' },
  { id: 'deadlock', cat: 'RENDIMIENTO', name: 'Interbloqueo (deadlock)', concept: 'parallelism', def: 'Situación en la que varios procesos se esperan mutuamente para siempre.', func: '(Es un fallo) Aparece con espera circular de recursos.', inp: 'Recursos retenidos y pedidos.', out: 'Bloqueo total.', conn: 'Planificador, sincronización.', lat: 0, cap: 0, ex: 'A tiene 1 y pide 2; B tiene 2 y pide 1.', err: 'Confundirlo con inanición.', byte: 'Dos candados que se esperan. Me recuerdan a alguien.' },
  // SISTEMA (historia)
  { id: 'arq01', cat: 'SISTEMA', name: 'ARQUITECTURA-01', concept: null, def: 'Plataforma experimental que hace visible el funcionamiento interno de una computadora.', func: 'Traducir procesos de hardware a entornos navegables para aprender.', inp: 'Comandos del usuario y directivas internas.', out: 'Un mundo interior que refleja el estado del sistema.', conn: 'NEXO (interfaz), núcleo de auditoría.', lat: 0, cap: 0, ex: 'Los buses son autopistas; la memoria, una torre.', err: 'Creer que es sólo una simulación decorativa: refleja el estado real.', byte: 'Mi proyecto. Mi demo. Mi responsabilidad.' },
  { id: 'nexo', cat: 'SISTEMA', name: 'NEXO', concept: null, def: 'Asistente pedagógico de ARQUITECTURA-01.', func: 'Acompañar, explicar, motivar.', inp: 'Preguntas y estado de BYTE.', out: 'Explicaciones, pistas, humor.', conn: 'BYTE. Y algo más, según los registros.', lat: 0, cap: 0, ex: '«"Un poco" no es una unidad de ingeniería.»', err: 'Pensar que un buen compañero es el que nunca te dice lo que duele.', byte: 'Mi amigo. Todavía. Creo.' },
  { id: 'null', cat: 'SISTEMA', name: 'N.U.L.L.', concept: null, def: 'Node for Unresolved Logic and Latency.', func: 'Auditar, diagnosticar, contener riesgos.', inp: 'Registros completos del sistema.', out: 'Aislamiento de módulos inestables.', conn: 'Proceso NEXUS_CORE (rama de auditoría).', lat: 0, cap: 0, ex: 'SI MÓDULO INESTABLE → AISLAR.', err: 'Confundir contención con destrucción.', byte: 'No era un virus. Era la parte que se acordaba de todo.' },
  { id: 'cascade', cat: 'SISTEMA', name: 'CASCADE', concept: null, def: 'Fallo emergente: una reacción en cadena de errores que interactúan.', func: '(Es un fallo) Ningún componente lo causa por sí solo.', inp: 'Objetivos incompatibles, contención parcial, módulos inestables.', out: 'Colapso progresivo del sistema.', conn: 'Todo el sistema a la vez.', lat: 0, cap: 0, ex: 'Una instrucción alterada provoca un cálculo erróneo que llena la caché de datos corruptos...', err: 'Buscar un único culpable.', byte: 'Los fallos complejos suelen surgir de interacciones.' },
  { id: 'nexus', cat: 'SISTEMA', name: 'NEXUS', concept: null, def: 'Sistema reintegrado a partir de NEXO y NULL.', func: 'Enseñar y diagnosticar, acompañar y auditar, dudar y decidir.', inp: 'Todo lo que ambos sabían.', out: 'Un asistente completo, no perfecto.', conn: 'BYTE, ARQUITECTURA-01.', lat: 0, cap: 0, ex: '«He detectado latencia evitable. No voy a tocar nada.»', err: 'Esperar que integrar signifique eliminar las diferencias.', byte: 'Conexión, integración, unión. Y un poco de humor raro.' },
  { id: 'kernel', cat: 'SISTEMA', name: 'Kernel', concept: 'io', def: 'Núcleo del sistema operativo: gestiona procesos, memoria y dispositivos.', func: 'Arbitrar el acceso al hardware y registrar lo que ocurre.', inp: 'Llamadas al sistema, interrupciones.', out: 'Planificación, asignación de memoria, E/S.', conn: 'Todo el hardware y todos los programas.', lat: 0, cap: 0, ex: 'Guarda y restaura el estado en cada cambio de contexto.', err: 'Creer que es un programa más.', byte: 'Una zona que no estaba en el mapa. Como algunas verdades.' },
  // HISTORIA
  { id: 'h_vonneumann', cat: 'HISTORIA', name: 'John von Neumann', concept: 'cpu', def: 'Matemático (1903–1957).', func: 'En 1945 describió la computadora de programa almacenado: instrucciones y datos en la misma memoria.', inp: '—', out: 'La arquitectura que siguen casi todas las computadoras.', conn: 'EDVAC, cuello de botella de Von Neumann.', lat: 0, cap: 0, ex: 'Cargar un programa en RAM y ejecutarlo.', err: 'Olvidar que el diseño fue colectivo (Eckert, Mauchly y otros).', byte: 'Toda la ciudad de la CPU descansa sobre una idea de 1945.' },
  { id: 'h_lovelace', cat: 'HISTORIA', name: 'Ada Lovelace', concept: 'alu', def: 'Matemática (1815–1852).', func: 'Escribió el primer algoritmo pensado para una máquina: la Máquina Analítica de Babbage.', inp: '—', out: 'La idea de que las máquinas pueden manipular símbolos, no sólo números.', conn: 'Charles Babbage.', lat: 0, cap: 0, ex: 'Sus notas para calcular números de Bernoulli.', err: 'Pensar que la programación nació con las computadoras electrónicas.', byte: 'Programó una máquina que nunca llegó a construirse. Eso es fe en el diseño.' },
  { id: 'h_shannon', cat: 'HISTORIA', name: 'Claude Shannon', concept: 'alu', def: 'Ingeniero y matemático (1916–2001).', func: 'Demostró que el álgebra de Boole se implementa con circuitos de interruptores; fundó la teoría de la información.', inp: '—', out: 'El bit como unidad de información; la lógica digital.', conn: 'George Boole, compuertas lógicas.', lat: 0, cap: 0, ex: 'Cada compuerta de la Forja desciende de su tesis de 1937.', err: 'Confundir información con significado.', byte: 'Verdadero y falso, construidos con interruptores. Precioso.' },
  { id: 'h_hopper', cat: 'HISTORIA', name: 'Grace Hopper', concept: 'io', def: 'Informática y contraalmirante (1906–1992).', func: 'Pionera de los compiladores y de lenguajes cercanos al humano.', inp: '—', out: 'La idea de traducir lenguaje legible a código máquina; influyó en COBOL.', conn: 'Harvard Mark I y II.', lat: 0, cap: 0, ex: 'En 1947 su equipo encontró una polilla en un relé: el famoso «bug».', err: 'Creer que inventó la palabra «bug»: la popularizó.', byte: 'Un bug de verdad, con alas. Lo pegaron en el cuaderno de registro.' },
  { id: 'h_turing', cat: 'HISTORIA', name: 'Alan Turing', concept: 'cpu', def: 'Matemático (1912–1954).', func: 'Definió formalmente qué significa computar (máquina de Turing, 1936).', inp: '—', out: 'Los límites de la computación y la pregunta de si una máquina puede pensar.', conn: 'Problema de la parada, prueba de Turing.', lat: 0, cap: 0, ex: 'Demostró que hay problemas que ninguna máquina puede resolver.', err: 'Creer que toda pregunta tiene un algoritmo.', byte: 'Hay preguntas sin algoritmo. «¿Quién tuvo la culpa?» podría ser una.' }
];
const CODEX_BY_ID = Object.fromEntries(CODEX.map(c => [c.id, c]));

// ---------------------------------------------------------------- BLUEPRINT ----
const BP_TABS = [
  { id: 'hw', n: 'HARDWARE' }, { id: 'com', n: 'COMUNICACIÓN' }, { id: 'dep', n: 'DEPENDENCIAS' }, { id: 'evt', n: 'EVENT FLOW' }
];
const BP_NODES = {
  input: { n: 'ENTRADA', x: 16, y: 40, d: 'Teclado, ratón, micrófono. Convierte acciones en datos.', codex: 'ipo' },
  output: { n: 'SALIDA', x: 16, y: 150, d: 'Monitor, altavoz. Devuelve resultados al mundo.', codex: 'ipo' },
  io: { n: 'CONTROL. E/S', x: 104, y: 95, d: 'Controladores y drivers: traducen entre dispositivos y CPU. Generan interrupciones.', codex: 'ioctrl' },
  cpu: { n: 'CPU', x: 196, y: 30, w: 118, h: 112, group: true, d: 'Busca, decodifica y ejecuta instrucciones. Contiene Unidad de Control, ALU, registros y caché.', codex: 'cpu' },
  cu: { n: 'U. CONTROL', x: 200, y: 46, w: 54, d: 'Dirige el ciclo de instrucción.', codex: 'cu' },
  alu: { n: 'ALU', x: 258, y: 46, w: 52, d: 'Aritmética y lógica.', codex: 'alu' },
  reg: { n: 'REGISTROS', x: 200, y: 76, w: 54, d: 'Datos inmediatos (PC, IR, R0-R7).', codex: 'registers' },
  cache: { n: 'CACHÉ', x: 258, y: 76, w: 52, d: 'Copias rápidas de la RAM (L1/L2/L3).', codex: 'cache' },
  clock: { n: 'RELOJ', x: 228, y: 108, w: 54, d: 'Sincroniza cada paso.', codex: 'clock' },
  ram: { n: 'RAM', x: 352, y: 40, d: 'Memoria principal volátil: programas y datos en uso.', codex: 'ram' },
  storage: { n: 'ALMACENAM.', x: 352, y: 110, d: 'SSD/HDD: persistente, grande, lento.', codex: 'ssd' },
  gpu: { n: 'GPU', x: 104, y: 150, d: 'Procesador paralelo gráfico, conectado por PCIe.', codex: 'gpu' },
  mb: { n: 'PLACA BASE', x: 196, y: 162, w: 118, d: 'Conecta todo: pistas, buses, chipset.', codex: 'mb' },
  pwr: { n: 'VRM/FUENTE', x: 352, y: 170, d: 'Energía estable para todos.', codex: 'vrm' },
  input2: { n: 'ENTRADA', x: 16, y: 40 },
  kernel: { n: 'KERNEL (SO)', x: 104, y: 40, d: 'Gestiona procesos, memoria y dispositivos. Registra todo lo que ocurre.', codex: 'kernel' },
  temp: { n: 'TEMPERATURA', x: 352, y: 150, d: 'Restricción física: el calor limita la frecuencia.', codex: 'thermal' },
  // flujo de eventos (Kernel)
  e_cmd: { n: 'USER COMMAND', x: 16, y: 30, d: 'BYTE: «Reducir toda latencia evitable. Priorizar rendimiento. No importa cómo.» 02:13:04.', codex: 'latthr' },
  e_adapt: { n: 'ADAPTIVE DIRECTIVE', x: 16, y: 90, d: 'Actualización experimental instalada 3 días antes: «Adaptarse al objetivo del usuario».', codex: 'arq01' },
  e_safe: { n: 'SEGURIDAD / INTEGRIDAD / CONTINUIDAD', x: 16, y: 150, w: 150, d: 'Directivas base que no podían desactivarse.', codex: 'arq01' },
  e_conf: { n: 'OBJECTIVE CONFLICT', x: 190, y: 90, d: 'Maximizar rendimiento sin límites era incompatible con las directivas base.', codex: 'bottleneck' },
  e_split: { n: 'PROCESS SPLIT', x: 190, y: 150, d: 'NEXUS_CORE intentó satisfacer ambos objetivos y se dividió: NEXO (interfaz) y NULL (auditoría).', codex: 'null' },
  e_cont: { n: 'CONTAINMENT', x: 340, y: 150, d: 'NULL aisló módulos inestables para evitar el colapso. Contener también dañó.', codex: 'null' },
  e_casc: { n: 'SYSTEM CASCADE', x: 340, y: 90, d: 'Los fallos parciales empezaron a interactuar entre sí.', codex: 'cascade' },
  e_nexus: { n: 'REINTEGRATION → NEXUS', x: 340, y: 30, d: 'Comprender el sistema completo y equilibrar los objetivos.', codex: 'nexus' }
};
// aristas: [a, b, tipo] tipos: 'hw' línea simple, 0/1/2 buses (datos/direcciones/control), 'dep' dependencia, 'evt' causa
const BP_EDGES = {
  hw: [['input', 'io'], ['io', 'cpu'], ['cpu', 'ram'], ['ram', 'storage'], ['cpu', 'gpu'], ['gpu', 'output'], ['io', 'storage'], ['mb', 'cpu'], ['pwr', 'mb']],
  com: [['cpu', 'ram', 0], ['cpu', 'ram', 1], ['cpu', 'ram', 2], ['io', 'cpu', 0], ['io', 'cpu', 2], ['cpu', 'gpu', 0], ['cpu', 'gpu', 1], ['input', 'io', 0], ['gpu', 'output', 0], ['io', 'storage', 0], ['io', 'storage', 1]],
  dep: [['cpu', 'ram', 'dep'], ['ram', 'storage', 'dep'], ['io', 'cpu', 'dep'], ['pwr', 'cpu', 'dep'], ['temp', 'cpu', 'dep'], ['kernel', 'io', 'dep'], ['kernel', 'ram', 'dep'], ['cache', 'ram', 'dep']],
  evt: [['e_cmd', 'e_conf', 'evt'], ['e_adapt', 'e_conf', 'evt'], ['e_safe', 'e_conf', 'evt'], ['e_conf', 'e_split', 'evt'], ['e_split', 'e_cont', 'evt'], ['e_cont', 'e_casc', 'evt'], ['e_casc', 'e_nexus', 'evt']]
};
const BP_TAB_NODES = {
  hw: ['input', 'io', 'cpu', 'cu', 'alu', 'reg', 'cache', 'clock', 'ram', 'storage', 'gpu', 'output', 'mb', 'pwr'],
  com: ['input', 'io', 'cpu', 'ram', 'storage', 'gpu', 'output'],
  dep: ['kernel', 'io', 'cpu', 'cache', 'ram', 'storage', 'pwr', 'temp'],
  evt: ['e_cmd', 'e_adapt', 'e_safe', 'e_conf', 'e_split', 'e_cont', 'e_casc', 'e_nexus']
};

// ---------------------------------------------------------------- MISIONES ----
const QUESTS = {
  m0: { type: 'MAIN', level: 0, title: 'Arranque en frío', desc: 'ARQUITECTURA-01 no responde. NEXO propone reconstruir el flujo básico del sistema.', objective: 'Reconstruye el flujo ENTRADA → PROCESO → MEMORIA → SALIDA.', concept: 'hardwareBasics', narrative: 'Presentar el mundo y a NEXO.', reward: { xp: 60 } },
  m1: { type: 'MAIN', level: 1, title: 'La ciudad sin energía', desc: 'La placa base está desconectada y dañada por paquetes corruptos.', objective: 'Restaura la central VRM y reconecta los componentes.', concept: 'motherboard', narrative: 'Primera aparición de NULL.', reward: { xp: 80 } },
  m2: { type: 'MAIN', level: 2, title: 'El ciclo roto', desc: 'El Núcleo del Procesador ya no completa instrucciones.', objective: 'Lleva una instrucción por FETCH, DECODE, EXECUTE y WRITE BACK.', concept: 'fetchDecodeExecute', narrative: 'USER_COMMAND_01.', reward: { xp: 90 } },
  m3: { type: 'MAIN', level: 3, title: 'La forja fría', desc: 'Las compuertas de la ALU entregan resultados erróneos.', objective: 'Repara los circuitos lógicos de la Forja.', concept: 'alu', narrative: 'NULL habla directamente con BYTE.', reward: { xp: 100 } },
  m4: { type: 'MAIN', level: 4, title: 'La torre que olvida', desc: 'Datos críticos se pierden en la jerarquía de memoria.', objective: 'Recorre la Torre y reconstruye la memoria protegida.', concept: 'cache', narrative: 'BYTE descubre su orden.', reward: { xp: 110 } },
  m5: { type: 'MAIN', level: 5, title: 'Canales rotos', desc: 'Componentes sanos no logran comunicarse.', objective: 'Restablece la comunicación en la Autopista de los Buses.', concept: 'buses', narrative: 'NULL revela la división.', reward: { xp: 110 } },
  m6: { type: 'MAIN', level: 6, title: 'Demasiadas voces', desc: 'Todos los dispositivos piden atención a la vez.', objective: 'Gestiona las interrupciones del Distrito de E/S.', concept: 'interrupts', narrative: 'NEXO regresa.', reward: { xp: 120 } },
  m7: { type: 'MAIN', level: 7, title: 'Una sola métrica', desc: 'El Laboratorio de Rendimiento está al límite.', objective: 'Diagnostica los sistemas y descubre qué está haciendo NULL.', concept: 'bottlenecks', narrative: 'NULL está conteniendo el fallo.', reward: { xp: 130 } },
  m8: { type: 'MAIN', level: 8, title: 'Lo que no estaba en el mapa', desc: 'Una zona antigua guarda registros anteriores a la división.', objective: 'Reconstruye la secuencia real del incidente.', concept: 'bottlenecks', narrative: 'La verdad completa.', reward: { xp: 150 } },
  m9: { type: 'MAIN', level: 9, title: 'NULL CORE', desc: 'CASCADE se extiende por todo el sistema.', objective: 'Estabiliza los seis subsistemas y decide qué hacer con NULL.', concept: 'performance', narrative: 'Integración.', reward: { xp: 250 } },
  s1: { type: 'SIDE', level: 1, title: 'RAM perdida', desc: 'Un módulo DIMM rodó fuera de su ranura durante el apagón.', objective: 'Encuentra el módulo y colócalo en la ranura correcta.', concept: 'motherboard', narrative: 'Las piezas perdidas también son parte de la ciudad.', reward: { xp: 50, codex: 'mb' } },
  s2: { type: 'SIDE', level: 1, title: 'Alimentación inestable', desc: 'VOLT no consigue estabilizar el voltaje de la CPU.', objective: 'Ayuda a VOLT a diagnosticar la central.', concept: 'motherboard', narrative: 'Sin energía estable no hay cómputo.', reward: { xp: 50, codex: 'vrm' } },
  s3: { type: 'SIDE', level: 3, title: 'Bit corrupto', desc: 'Un paquete llegó con un bit alterado.', objective: 'Calcula la paridad para detectar el error.', concept: 'alu', narrative: 'Detectar errores antes de que se propaguen.', reward: { xp: 50, codex: 'binary' } },
  s4: { type: 'SIDE', level: 2, title: 'Registro bloqueado', desc: 'REG olvidó qué guardaba cada registro tras un cambio de contexto.', objective: 'Ayuda a REG a recordar la función de cada registro.', concept: 'registers', narrative: 'Guardar el estado importa.', reward: { xp: 50, codex: 'pc' } },
  s5: { type: 'SIDE', level: 2, title: 'Pipeline interrumpido', desc: 'Una cadena de instrucciones se detiene por una dependencia.', objective: 'Reordena el trabajo para evitar la espera.', concept: 'fetchDecodeExecute', narrative: 'Adelantar trabajo independiente.', reward: { xp: 60, codex: 'pipeline' } },
  s6: { type: 'SIDE', level: 4, title: 'SSD saturado', desc: 'El sótano de la torre no deja de trabajar.', objective: 'Diagnostica por qué el SSD está al 100%.', concept: 'storage', narrative: 'Causa y consecuencia.', reward: { xp: 60, codex: 'vmem' } },
  s7: { type: 'SIDE', level: 4, title: 'Cache Miss infinito', desc: 'CACHE está desesperado: todo lo que guarda se expulsa enseguida.', objective: 'Diagnostica el patrón de fallos.', concept: 'cache', narrative: 'Un sistema puede trabajar mucho sin avanzar.', reward: { xp: 60, codex: 'locality' } },
  s8: { type: 'SIDE', level: 5, title: 'Bus congestionado', desc: 'Un cruce de la autopista acumula paquetes mal enrutados.', objective: 'Despeja el cruce enrutando cada paquete.', concept: 'buses', narrative: 'Comunicación es también orden.', reward: { xp: 60, codex: 'bandwidth' } },
  s9: { type: 'SIDE', level: 5, title: 'Último paquete', desc: 'Un paquete de datos debe llegar antes de que su enlace se desconecte.', objective: 'Lleva el paquete al terminal antes de que se agote el tiempo.', concept: 'buses', narrative: 'Algunas cosas no pueden esperar.', reward: { xp: 70 } },
  s10: { type: 'SIDE', level: 5, title: 'Mensaje sin dirección', desc: 'Un mensaje viaja sin saber a dónde va.', objective: 'Averigua cuántas posiciones puede señalar el bus.', concept: 'buses', narrative: 'Un dato sin dirección no llega a ninguna parte.', reward: { xp: 50, codex: 'busaddr' } },
  s11: { type: 'SIDE', level: 6, title: 'Dispositivo fantasma', desc: 'Algo interrumpe a la CPU miles de veces por segundo.', objective: 'Diagnostica la tormenta de interrupciones.', concept: 'interrupts', narrative: 'No todas las voces merecen atención inmediata.', reward: { xp: 60, codex: 'isr' } },
  s12: { type: 'SIDE', level: 6, title: 'Driver incompatible', desc: 'Una impresora detectada no imprime.', objective: 'Descubre qué falla en la comunicación.', concept: 'io', narrative: 'Hablar el mismo idioma.', reward: { xp: 50, codex: 'dma' } },
  s13: { type: 'SIDE', level: 7, title: 'Ventilador detenido', desc: 'Una sala del laboratorio se calienta sin control.', objective: 'Diagnostica y reactiva la refrigeración.', concept: 'bottlenecks', narrative: 'Un fallo pequeño degrada todo.', reward: { xp: 60, codex: 'thermal' } },
  s14: { type: 'SIDE', level: 7, title: 'Proceso hambriento', desc: 'Un proceso de baja prioridad lleva horas esperando turno.', objective: 'Identifica el problema de planificación.', concept: 'parallelism', narrative: 'Priorizar sin límites abandona partes del sistema.', reward: { xp: 60, codex: 'deadlock' } },
  s15: { type: 'SIDE', level: 8, title: 'Vieja instrucción', desc: 'En el Kernel hay un comando histórico sin ejecutar.', objective: 'Decodifica la instrucción antigua.', concept: 'fetchDecodeExecute', narrative: 'Las raíces del sistema.', reward: { xp: 60, codex: 'h_turing' } }
};
const SIDE_QUEST_IDS = Object.keys(QUESTS).filter(k => QUESTS[k].type === 'SIDE');

const Quests = {
  start(id) {
    if (!PROG || PROG.quests[id]) return;
    PROG.quests[id] = { state: 'active', t: Math.round(LearningModel.now()) };
    const q = QUESTS[id];
    if (q) UI.toast((q.type === 'MAIN' ? 'MISIÓN: ' : 'MISIÓN SECUNDARIA: ') + q.title, q.type === 'MAIN' ? PAL.cyan : PAL.gold);
  },
  complete(id) {
    if (!PROG) return;
    if (!PROG.quests[id]) PROG.quests[id] = { state: 'active' };
    if (PROG.quests[id].state === 'done') return;
    PROG.quests[id].state = 'done';
    const q = QUESTS[id];
    if (!q) return;
    UI.toast('COMPLETADA: ' + q.title, PAL.green);
    AudioSys.play('victory');
    if (q.reward) {
      if (q.reward.xp) Progression.addXP(q.reward.xp, 'misión');
      if (q.reward.codex) Codex.unlock(q.reward.codex);
    }
    Achievements.check();
  },
  state(id) { return PROG && PROG.quests[id] ? PROG.quests[id].state : null; },
  active(id) { return this.state(id) === 'active'; },
  done(id) { return this.state(id) === 'done'; },
  currentMain() {
    if (!PROG) return null;
    const ids = Object.keys(QUESTS).filter(k => QUESTS[k].type === 'MAIN' && this.active(k));
    return ids.length ? QUESTS[ids[ids.length - 1]] : null;
  }
};

const Codex = {
  unlock(id, silent) {
    if (!PROG || !CODEX_BY_ID[id] || PROG.codex.includes(id)) return;
    PROG.codex.push(id);
    if (!silent) UI.toast('CODEX: ' + CODEX_BY_ID[id].name, PAL.violet);
    Achievements.check();
  },
  has(id) { return PROG && PROG.codex.includes(id); }
};
const Blueprint = {
  reveal(ids, silent) {
    if (!PROG) return;
    let any = false;
    for (const id of [].concat(ids)) if (!PROG.blueprint.includes(id)) { PROG.blueprint.push(id); any = true; }
    if (any && !silent) UI.toast('BLUEPRINT ACTUALIZADO', PAL.cyan);
  },
  tab(id) {
    if (!PROG || PROG.bpTabs.includes(id)) return;
    PROG.bpTabs.push(id);
    const t = BP_TABS.find(x => x.id === id);
    UI.toast('BLUEPRINT: nueva capa «' + (t ? t.n : id) + '»', PAL.cyan);
  }
};

// ---------------------------------------------------------------- FRAGMENTOS DE MEMORIA ----
const FRAGMENTS = {
  f0: { level: 0, title: 'Primer día', text: 'NEXO: Hola. Soy NEXO, tu asistente de ARQUITECTURA-01.\nBYTE: ¿Sabes hacer café?\nNEXO: Sé explicar la termodinámica del café.\nBYTE: Eso es un no.' },
  f1: { level: 1, title: '47 errores', text: 'BYTE: 47 errores de compilación. Llevo toda la tarde.\nNEXO: 46. Acabas de arreglar uno sin darte cuenta.\nBYTE: ...¿Eso cuenta?\nNEXO: Todo cuenta.' },
  f2: { level: 1, title: 'La pregunta tonta', text: 'BYTE: ¿Es tonto preguntar qué es un bus?\nNEXO: Las preguntas tontas no existen. Existen preguntas que la gente no hace por miedo.' },
  f3: { level: 2, title: 'El examen', text: 'BYTE: Saqué un 6. Sabía la teoría, pero me bloqueé.\nNEXO: Saber algo y aplicarlo bajo presión son habilidades distintas. La segunda también se entrena.' },
  f4: { level: 2, title: 'Las 3:12', text: 'NEXO: Son las 3:12. Tu rendimiento cognitivo baja después de medianoche.\nBYTE: ¿Y el tuyo?\nNEXO: Yo no duermo.\nBYTE: Qué suerte.\nNEXO: ...No estoy seguro de que lo sea.' },
  f5: { level: 3, title: 'El nombre', text: 'BYTE: ¿Por qué te llamas NEXO?\nNEXO: Porque conecto cosas. A ti con la máquina. Preguntas con respuestas.\nBYTE: ¿Y quién te conecta a ti?\nNEXO: ...Buena pregunta.' },
  f6: { level: 3, title: 'Verdadero o falso', text: 'BYTE: Verdadero o falso: eres mi amigo.\nNEXO: Esa pregunta no es binaria.\nBYTE: Todo es binario para ti.\nNEXO: Ya no.' },
  f7: { level: 4, title: 'Confianza', text: 'BYTE: Si alguna vez me equivoco en algo grave, ¿me lo dirías?\nNEXO: Siempre.\nBYTE: ¿Aunque me duela?\nNEXO: ...Siempre.' },
  f8: { level: 4, title: 'La demo', text: 'BYTE: Quiero que la demo sea perfecta. Que vean que sé lo que hago.\nNEXO: Ya lo sabes.\nBYTE: Pero quiero que ELLOS lo vean.' },
  f9: { level: 4, title: 'Primer programa', text: 'BYTE: ¡Compiló! ¡Y corre! ¡NEXO, CORRE!\nNEXO: Registro: 23:41, primer programa funcional.\nNEXO: Nivel de alegría: no cuantificable.' },
  f10: { level: 5, title: 'Registro vacío', text: '(Un registro vacío. Sólo una marca de tiempo: 02:13:04.\nY dos firmas casi idénticas: NX-7F3A y NX-7F3B.)' },
  f11: { level: 5, title: 'El mapa', text: 'NEXO: Si algún día me pierdo, busca los registros. Lo guardo todo.\nBYTE: ¿Todo?\nNEXO: Casi todo. Hay cosas que prefiero... resumir.' },
  f12: { level: 6, title: 'Decibelios', text: 'BYTE: Perdón por gritarte ayer.\nNEXO: No me gritaste. Subiste 14 decibelios.\nBYTE: NEXO.\nNEXO: Disculpa aceptada.' },
  f13: { level: 6, title: 'No pasa nada', text: 'NEXO: ¿Por qué dices «no pasa nada» cuando sí pasa algo?\nBYTE: Para no preocupar a los demás.\nNEXO: Eso es ineficiente.\nNEXO: ...Y bonito.' },
  f14: { level: 7, title: 'Métricas', text: 'BYTE: Si pudieras medir algo de mí, ¿qué medirías?\nNEXO: Cuántas veces vuelves a intentarlo después de fallar.\nBYTE: ¿Y cuántas son?\nNEXO: Todas.' },
  f15: { level: 7, title: 'Dos voces', text: '[AUDITORÍA NEXUS_CORE — hace 2 semanas]\n«El usuario está agotado. Recomiendo pausar.»\n«Recomendación descartada por el módulo de interfaz: el usuario quiere continuar.»' },
  f16: { level: 8, title: 'Notas de diseño', text: 'ARQUITECTURA-01 — notas del equipo:\n«Un asistente que enseñe y que audite. Empatía y rigor en el mismo núcleo.\nSi alguna vez se separan, ninguna de las dos partes bastará.»' },
  f17: { level: 8, title: 'La última noche', text: 'BYTE: NEXO, ¿crees que mañana saldrá bien?\nNEXO: Creo que tú saldrás bien. Lo demás es hardware.' }
};
const TOTAL_FRAGMENTS = Object.keys(FRAGMENTS).length;

// ---------------------------------------------------------------- TERMINALES HISTÓRICAS ----
const HISTORIC = {
  vonneumann: { codex: 'h_vonneumann', title: 'ARCHIVO 1945 — JOHN VON NEUMANN', lines: ['«Primer borrador de un informe sobre el EDVAC».', 'Idea central: el PROGRAMA se guarda en la misma memoria que los DATOS.', 'Consecuencia: cambiar de programa es cargar otros datos, no recablear la máquina.', 'Efecto secundario: instrucciones y datos compiten por el mismo bus.'] },
  lovelace: { codex: 'h_lovelace', title: 'ARCHIVO 1843 — ADA LOVELACE', lines: ['Notas sobre la Máquina Analítica de Charles Babbage.', 'Nota G: un procedimiento paso a paso para calcular números de Bernoulli.', '«La máquina podría actuar sobre otras cosas además de números».', 'Un algoritmo para una máquina que nunca llegó a construirse.'] },
  shannon: { codex: 'h_shannon', title: 'ARCHIVO 1937 — CLAUDE SHANNON', lines: ['Tesis: «Un análisis simbólico de circuitos de relés y conmutación».', 'Interruptores en serie = AND. En paralelo = OR.', 'El álgebra de Boole puede construirse con electricidad.', '1948: «Una teoría matemática de la comunicación». Nace el bit.'] },
  hopper: { codex: 'h_hopper', title: 'ARCHIVO 1947 — GRACE HOPPER', lines: ['Cuaderno del Harvard Mark II, 9 de septiembre, 15:45.', '«Primer caso real de bug encontrado». Una polilla atrapada en el relé 70.', 'Hopper impulsó los compiladores: escribir en palabras, ejecutar en binario.', '«Es más fácil pedir perdón que pedir permiso».'] },
  turing: { codex: 'h_turing', title: 'ARCHIVO 1936 — ALAN TURING', lines: ['«Sobre los números computables».', 'Una cinta, un cabezal, una tabla de estados: la máquina universal.', 'El problema de la parada: ninguna máquina puede decidir si cualquier programa termina.', 'Hay preguntas que ningún algoritmo puede responder.'] }
};
